[project]
name = "pydantic-state-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-settings>=2.9.1",
    "pydantic>=2.11.3",
    "redis>=5.2.1",
]
