[project]
name = "pydantic-state"
version = "0.0.7"
description = "Python package for distributed state"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pydantic-settings>=2.9.1", "pydantic>=2.11.3", "redis>=5.2.1"]

[tool.pyright]
venvPath = "."
venv = ".venv"
