# .github/workflows/publish.yml
name: Publish Python package

# Trigger on push or merge to main
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install uv (pin to a known version if you like)
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2" # optional :contentReference[oaicite:0]{index=0}

      # 3. Select the Python version as defined in your project
      - name: Set up Python
        run: uv python install # respects your pyproject.toml or .python-version :contentReference[oaicite:1]{index=1}

      # 4. Build source and wheel distributions
      - name: Build distributions
        run: uv build --no-sources # ensure no extra sources are used :contentReference[oaicite:2]{index=2}

      # 5. Publish to PyPI
      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish # token-based upload :contentReference[oaicite:3]{index=3}
